# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-14 05:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='activity',
            fields=[
                ('activity_no', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('activity_name', models.CharField(max_length=20)),
                ('organization_no', models.CharField(max_length=10)),
                ('activity_description', models.CharField(max_length=100)),
                ('activity_time', models.DateTimeField()),
                ('activity_num_of_participate', models.IntegerField()),
                ('last_apply_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'dor_activity',
            },
        ),
        migrations.CreateModel(
            name='activity_applyment',
            fields=[
                ('sno', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('activity_no', models.CharField(max_length=10)),
                ('is_apply_cancel', models.CharField(max_length=1)),
                ('is_apply_success', models.CharField(max_length=1)),
                ('apply_time', models.DateTimeField()),
                ('ad_no', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'dor_activity_applyment',
            },
        ),
        migrations.CreateModel(
            name='admin_account',
            fields=[
                ('ad_no', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=20, null=True)),
                ('password', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'dor_admin_account',
            },
        ),
        migrations.CreateModel(
            name='adminstrator',
            fields=[
                ('adminstrator_no', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('adminstrator_name', models.CharField(max_length=20)),
                ('adminstrator_phone', models.CharField(max_length=11)),
                ('dor_no', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'dor_adminstrator',
            },
        ),
        migrations.CreateModel(
            name='bill',
            fields=[
                ('sno', models.CharField(max_length=10)),
                ('bill_no', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('item', models.CharField(max_length=20)),
                ('fee', models.FloatField()),
                ('time', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'dor_bill',
            },
        ),
        migrations.CreateModel(
            name='book',
            fields=[
                ('book_no', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('from_student', models.CharField(max_length=10)),
                ('book_description', models.CharField(max_length=10)),
                ('book_class', models.CharField(max_length=20)),
                ('is_borrowed', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'dor_book',
            },
        ),
        migrations.CreateModel(
            name='book_applyment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_no', models.CharField(max_length=10)),
                ('sno', models.CharField(max_length=10)),
                ('is_apply_cancel', models.CharField(max_length=1)),
                ('is_apply_success', models.CharField(max_length=1)),
                ('apply_time', models.DateTimeField()),
                ('ad_no', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'dor_book_applyment',
            },
        ),
        migrations.CreateModel(
            name='device',
            fields=[
                ('device_no', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('device_name', models.CharField(max_length=10)),
                ('device_description', models.CharField(max_length=100)),
                ('device_amount', models.IntegerField()),
                ('device_applied_amount', models.IntegerField()),
            ],
            options={
                'db_table': 'dor_device',
            },
        ),
        migrations.CreateModel(
            name='device_applyment',
            fields=[
                ('sno', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('device_no', models.CharField(max_length=10)),
                ('from_time', models.DateTimeField()),
                ('dor_no', models.CharField(max_length=10)),
                ('is_apply_cancel', models.CharField(max_length=1)),
                ('is_apply_success', models.CharField(max_length=1)),
                ('return_device_time', models.DateTimeField()),
                ('ad_no', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'dor_device_applyment',
            },
        ),
        migrations.CreateModel(
            name='dor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dor_no', models.CharField(max_length=10)),
                ('sno', models.CharField(max_length=10)),
                ('room_no', models.CharField(max_length=10)),
                ('bed_no', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'dor_dor',
            },
        ),
        migrations.CreateModel(
            name='dor_applyment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.CharField(max_length=10)),
                ('sname', models.CharField(max_length=20)),
                ('dor_no', models.CharField(max_length=10)),
                ('room_no', models.CharField(max_length=10)),
                ('apply_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'dor_dor_applyment',
            },
        ),
        migrations.CreateModel(
            name='dor_cancel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.CharField(max_length=10)),
                ('sname', models.CharField(max_length=20)),
                ('dor_no', models.CharField(max_length=10)),
                ('room_no', models.CharField(max_length=10)),
                ('apply_time', models.DateTimeField()),
                ('phone', models.CharField(max_length=11)),
                ('reason', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'dor_dor_cancel',
            },
        ),
        migrations.CreateModel(
            name='dor_change',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.CharField(max_length=10)),
                ('sname', models.CharField(max_length=20)),
                ('old_dor_no', models.CharField(max_length=10)),
                ('old_room_no', models.CharField(max_length=10)),
                ('new_dor_no', models.CharField(max_length=10)),
                ('new_room_no', models.CharField(max_length=10)),
                ('apply_time', models.DateTimeField()),
                ('phone', models.CharField(max_length=11)),
                ('reason', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'dor_dor_change',
            },
        ),
        migrations.CreateModel(
            name='dormintory',
            fields=[
                ('dor_no', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('dor_name', models.CharField(max_length=20)),
                ('dor_description', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'dor_dormintory',
            },
        ),
        migrations.CreateModel(
            name='live_on_vacation',
            fields=[
                ('sno', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('sname', models.CharField(blank=True, max_length=20, null=True)),
                ('dor_no', models.CharField(blank=True, max_length=10, null=True)),
                ('from_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=11, null=True)),
            ],
            options={
                'db_table': 'dor_live_on_vacation',
            },
        ),
        migrations.CreateModel(
            name='live_on_vacation_applyment',
            fields=[
                ('sno', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('dor_no', models.CharField(max_length=10)),
                ('from_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('is_apply_cancel', models.CharField(max_length=1)),
                ('is_apply_success', models.CharField(max_length=1)),
                ('ad_no', models.CharField(max_length=10)),
                ('reason', models.CharField(max_length=100)),
                ('sname', models.CharField(max_length=20)),
                ('apply_time', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'dor_live_on_vacation_applyment',
            },
        ),
        migrations.CreateModel(
            name='meeting_room',
            fields=[
                ('meeting_room_no', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('meeting_room_size', models.CharField(max_length=10)),
                ('medium', models.CharField(max_length=1)),
                ('meeting_room_description', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'dor_meeting_room',
            },
        ),
        migrations.CreateModel(
            name='meeting_room_applyment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_room_no', models.CharField(max_length=10)),
                ('sno', models.CharField(max_length=10)),
                ('is_apply_cancel', models.CharField(max_length=1)),
                ('is_apply_success', models.CharField(max_length=1)),
                ('apply_time', models.DateTimeField()),
                ('ad_no', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'dor_meeting_room_applyment',
            },
        ),
        migrations.CreateModel(
            name='meeting_room_time_quantunum',
            fields=[
                ('meeting_room_time_quantunum', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('from_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'dor_meeting_room_time_quantunum',
            },
        ),
        migrations.CreateModel(
            name='organization',
            fields=[
                ('organization_no', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('organization_name', models.CharField(max_length=20)),
                ('organization_description', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'dor_organization',
            },
        ),
        migrations.CreateModel(
            name='pay_bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.CharField(max_length=10)),
                ('bill_no', models.CharField(max_length=10)),
                ('is_paied', models.CharField(max_length=1)),
                ('pay_time', models.DateTimeField()),
                ('dor_no', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'dor_pay_bill',
            },
        ),
        migrations.CreateModel(
            name='repair_device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.CharField(max_length=10)),
                ('dor_no', models.CharField(max_length=10)),
                ('room_no', models.CharField(max_length=10)),
                ('mobilephone', models.CharField(max_length=11)),
                ('description', models.CharField(max_length=100)),
                ('apply_time', models.DateTimeField()),
                ('ad_no', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'dor_repair_device',
            },
        ),
        migrations.CreateModel(
            name='room',
            fields=[
                ('room_no', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('dor_no', models.CharField(max_length=10)),
                ('bed_counts', models.IntegerField()),
                ('room_description', models.CharField(max_length=100)),
                ('empty_beds', models.IntegerField()),
            ],
            options={
                'db_table': 'dor_room',
            },
        ),
        migrations.CreateModel(
            name='routine_applyments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apply_time', models.DateTimeField()),
                ('sno', models.CharField(max_length=10)),
                ('dor_no', models.CharField(max_length=10)),
                ('room_no', models.CharField(max_length=10)),
                ('bed_no', models.CharField(max_length=10)),
                ('apply_content', models.CharField(max_length=100)),
                ('ad_no', models.CharField(max_length=10)),
                ('apply_status', models.CharField(max_length=20)),
                ('detail', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'dor_routine_applyments',
            },
        ),
        migrations.CreateModel(
            name='Stu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='stu_account',
            fields=[
                ('sno', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=20, null=True)),
                ('password', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'dor_stu_account',
            },
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('sno', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('sname', models.CharField(max_length=20)),
                ('college_no', models.CharField(max_length=20)),
                ('major_no', models.CharField(max_length=20)),
                ('grade', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=1)),
                ('dor_no', models.CharField(max_length=10)),
                ('room_no', models.CharField(max_length=10)),
                ('mobilephone', models.CharField(max_length=11)),
                ('email', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'dor_student',
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='vacation_time_quantum',
            fields=[
                ('vacation_time_quantunum', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('from_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'dor_vacation_time_quantum',
            },
        ),
        migrations.AlterUniqueTogether(
            name='routine_applyments',
            unique_together=set([('sno', 'apply_time')]),
        ),
        migrations.AlterUniqueTogether(
            name='repair_device',
            unique_together=set([('sno', 'apply_time')]),
        ),
        migrations.AlterUniqueTogether(
            name='pay_bill',
            unique_together=set([('sno', 'bill_no', 'is_paied')]),
        ),
        migrations.AlterUniqueTogether(
            name='meeting_room_applyment',
            unique_together=set([('meeting_room_no', 'sno', 'apply_time')]),
        ),
        migrations.AlterUniqueTogether(
            name='dor_change',
            unique_together=set([('sno', 'old_dor_no', 'old_room_no')]),
        ),
        migrations.AlterUniqueTogether(
            name='dor_cancel',
            unique_together=set([('sno', 'dor_no', 'room_no')]),
        ),
        migrations.AlterUniqueTogether(
            name='dor_applyment',
            unique_together=set([('sno', 'dor_no', 'room_no')]),
        ),
        migrations.AlterUniqueTogether(
            name='dor',
            unique_together=set([('dor_no', 'sno', 'room_no', 'bed_no')]),
        ),
        migrations.AlterUniqueTogether(
            name='book_applyment',
            unique_together=set([('book_no', 'sno', 'apply_time')]),
        ),
    ]
