# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-09 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dor', '0003_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='activity',
            fields=[
                ('activity_no', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('activity_name', models.CharField(max_length=20)),
                ('organization_no', models.CharField(max_length=10)),
                ('activity_description', models.CharField(max_length=100)),
                ('activity_time', models.DateTimeField()),
                ('activity_num_of_participate', models.IntegerField()),
                ('last_apply_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='activity_applyment',
            fields=[
                ('sno', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('activity_no', models.CharField(max_length=10)),
                ('is_apply_cancel', models.CharField(choices=[('T', 'true'), ('F', 'false')], max_length=1)),
                ('is_apply_success', models.CharField(choices=[('T', 'true'), ('F', 'false')], max_length=1)),
                ('apply_time', models.DateTimeField()),
                ('ad_no', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='adminstrator',
            fields=[
                ('adminstrator_no', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('adminstrator_name', models.CharField(max_length=20)),
                ('adminstrator_phone', models.CharField(max_length=11)),
                ('dor_no', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='bill',
            fields=[
                ('sno', models.CharField(max_length=10)),
                ('bill_no', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('item', models.CharField(max_length=20)),
                ('fee', models.FloatField()),
                ('time', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='book',
            fields=[
                ('book_no', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('from_student', models.CharField(max_length=10)),
                ('book_description', models.CharField(max_length=10)),
                ('book_class', models.CharField(max_length=20)),
                ('is_borrowed', models.CharField(choices=[('T', 'true'), ('F', 'false')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='book_applyment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_no', models.CharField(max_length=10)),
                ('sno', models.CharField(max_length=10)),
                ('is_apply_cancel', models.CharField(choices=[('T', 'true'), ('F', 'false')], max_length=1)),
                ('is_apply_success', models.CharField(choices=[('T', 'true'), ('F', 'false')], max_length=1)),
                ('apply_time', models.DateTimeField()),
                ('ad_no', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='device',
            fields=[
                ('device_no', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('device_name', models.CharField(max_length=10)),
                ('device_description', models.CharField(max_length=100)),
                ('device_amount', models.IntegerField()),
                ('device_applied_amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='device_applyment',
            fields=[
                ('sno', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('device_no', models.CharField(max_length=10)),
                ('from_time', models.DateTimeField()),
                ('dor_no', models.CharField(max_length=10)),
                ('is_apply_cancel', models.CharField(choices=[('T', 'true'), ('F', 'false')], max_length=1)),
                ('is_apply_success', models.CharField(choices=[('T', 'true'), ('F', 'false')], max_length=1)),
                ('return_device_time', models.DateTimeField()),
                ('ad_no', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='dor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dor_no', models.CharField(max_length=10)),
                ('sno', models.CharField(max_length=10)),
                ('room_no', models.CharField(max_length=10)),
                ('bed_no', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='dor_applyment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.CharField(max_length=10)),
                ('sname', models.CharField(max_length=20)),
                ('dor_no', models.CharField(max_length=10)),
                ('room_no', models.CharField(max_length=10)),
                ('apply_time', models.DateTimeField()),
                ('apply_status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='dor_cancel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.CharField(max_length=10)),
                ('sname', models.CharField(max_length=20)),
                ('dor_no', models.CharField(max_length=10)),
                ('room_no', models.CharField(max_length=10)),
                ('apply_time', models.DateTimeField()),
                ('apply_status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='dor_change',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.CharField(max_length=10)),
                ('sname', models.CharField(max_length=20)),
                ('old_dor_no', models.CharField(max_length=10)),
                ('old_room_no', models.CharField(max_length=10)),
                ('new_dor_no', models.CharField(max_length=10)),
                ('new_room_no', models.CharField(max_length=10)),
                ('apply_time', models.DateTimeField()),
                ('apply_status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='dormintory',
            fields=[
                ('dor_no', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('dor_name', models.CharField(max_length=20)),
                ('dor_description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='live_on_vacation',
            fields=[
                ('sno', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('dor_no', models.CharField(max_length=10)),
                ('from_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('is_apply_cancel', models.CharField(choices=[('T', 'true'), ('F', 'false')], max_length=1)),
                ('is_apply_success', models.CharField(choices=[('T', 'true'), ('F', 'false')], max_length=1)),
                ('ad_no', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='meeting_room',
            fields=[
                ('meeting_room_no', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('meeting_room_size', models.CharField(max_length=10)),
                ('medium', models.CharField(choices=[('T', 'true'), ('F', 'false')], max_length=1)),
                ('meeting_room_description', models.CharField(max_length=20)),
                ('is_occupied', models.CharField(choices=[('T', 'true'), ('F', 'false')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='meeting_room_applyment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_room_no', models.CharField(max_length=10)),
                ('sno', models.CharField(max_length=10)),
                ('is_apply_cancel', models.CharField(choices=[('T', 'true'), ('F', 'false')], max_length=1)),
                ('is_apply_success', models.CharField(choices=[('T', 'true'), ('F', 'false')], max_length=1)),
                ('apply_time', models.DateTimeField()),
                ('ad_no', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='meeting_room_time_quantunum',
            fields=[
                ('meeting_room_time_quantunum', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('from_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='organization',
            fields=[
                ('organization_no', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('organization_name', models.CharField(max_length=20)),
                ('organization_description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='pay_bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.CharField(max_length=10)),
                ('bill_no', models.CharField(max_length=10)),
                ('is_paied', models.CharField(choices=[('T', 'true'), ('F', 'false')], max_length=1)),
                ('pay_time', models.DateTimeField()),
                ('dor_no', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='repair_device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.CharField(max_length=10)),
                ('dor_no', models.CharField(max_length=10)),
                ('room_no', models.CharField(max_length=10)),
                ('mobilephone', models.CharField(max_length=11)),
                ('description', models.CharField(max_length=100)),
                ('apply_time', models.DateTimeField()),
                ('ad_no', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='room',
            fields=[
                ('room_no', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('dor_no', models.CharField(max_length=10)),
                ('bed_counts', models.IntegerField()),
                ('room_description', models.CharField(max_length=100)),
                ('empty_beds', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='routine_applyments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apply_time', models.DateTimeField()),
                ('sno', models.CharField(max_length=10)),
                ('dor_no', models.CharField(max_length=10)),
                ('room_no', models.CharField(max_length=10)),
                ('bed_no', models.CharField(max_length=10)),
                ('apply_content', models.CharField(max_length=100)),
                ('ad_no', models.CharField(max_length=10)),
                ('apply_status', models.CharField(max_length=20)),
                ('detail', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='vacation_time_quantum',
            fields=[
                ('vacation_time_quantunum', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('from_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
            ],
        ),
    ]
