# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-09 23:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dor', '0004_activity_activity_applyment_adminstrator_bill_book_book_applyment_device_device_applyment_dor_dor_ap'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='book_applyment',
            unique_together=set([('book_no', 'sno', 'apply_time')]),
        ),
        migrations.RemoveField(
            model_name='dor_applyment',
            name='apply_status',
        ),
        migrations.AlterUniqueTogether(
            name='dor_applyment',
            unique_together=set([('sno', 'dor_no', 'room_no')]),
        ),
        migrations.RemoveField(
            model_name='dor_cancel',
            name='apply_status',
        ),
        migrations.AlterUniqueTogether(
            name='dor_cancel',
            unique_together=set([('sno', 'dor_no', 'room_no')]),
        ),
        migrations.RemoveField(
            model_name='dor_change',
            name='apply_status',
        ),
        migrations.AlterUniqueTogether(
            name='dor_change',
            unique_together=set([('sno', 'old_dor_no', 'old_room_no')]),
        ),
        migrations.AlterUniqueTogether(
            name='meeting_room_applyment',
            unique_together=set([('meeting_room_no', 'sno', 'apply_time')]),
        ),
        migrations.AlterUniqueTogether(
            name='pay_bill',
            unique_together=set([('sno', 'bill_no', 'is_paied')]),
        ),
        migrations.AlterUniqueTogether(
            name='repair_device',
            unique_together=set([('sno', 'apply_time')]),
        ),
        migrations.AlterUniqueTogether(
            name='routine_applyments',
            unique_together=set([('sno', 'apply_time')]),
        ),
    ]
