# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-10 03:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dor', '0005_auto_20170910_0749'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dor',
            unique_together=set([('dor_no', 'sno', 'room_no', 'bed_no')]),
        ),
    ]
