# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-10 07:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dor', '0006_auto_20170910_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='dor_cancel',
            name='phone',
            field=models.CharField(default='0', max_length=11),
        ),
        migrations.AddField(
            model_name='dor_cancel',
            name='reason',
            field=models.CharField(default='\u65e0', max_length=100),
        ),
        migrations.AddField(
            model_name='dor_change',
            name='phone',
            field=models.CharField(default='0', max_length=11),
        ),
        migrations.AddField(
            model_name='dor_change',
            name='reason',
            field=models.CharField(default='\u65e0', max_length=100),
        ),
        migrations.AddField(
            model_name='live_on_vacation',
            name='reason',
            field=models.CharField(default='\u65e0', max_length=100),
        ),
    ]
