# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-10 08:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dor', '0007_auto_20170910_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='live_on_vacation',
            name='sname',
            field=models.CharField(default='', max_length=20),
        ),
    ]
