# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-14 00:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dor', '0008_live_on_vacation_sname'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='admin_account',
            fields=[
                ('ad_no', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=20, null=True)),
                ('password', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'dor_admin_account',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='admin_show_change_dor_log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.CharField(max_length=10)),
                ('sname', models.CharField(max_length=20)),
                ('old_dor_no', models.CharField(max_length=10)),
                ('old_room_no', models.CharField(max_length=10)),
                ('new_dor_no', models.CharField(max_length=10)),
                ('new_room_no', models.CharField(max_length=10)),
                ('apply_time', models.DateTimeField()),
                ('phone', models.CharField(max_length=11)),
                ('reason', models.CharField(max_length=100)),
                ('college_no', models.CharField(max_length=20)),
                ('major_no', models.CharField(max_length=20)),
                ('mobilephone', models.CharField(max_length=11)),
                ('email', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='live_on_vacation_applyment',
            fields=[
                ('sno', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('dor_no', models.CharField(max_length=10)),
                ('from_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('is_apply_cancel', models.CharField(max_length=1)),
                ('is_apply_success', models.CharField(max_length=1)),
                ('ad_no', models.CharField(max_length=10)),
                ('reason', models.CharField(max_length=100)),
                ('sname', models.CharField(max_length=20)),
                ('apply_time', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'dor_live_on_vacation_applyment',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='stu_account',
            fields=[
                ('sno', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=20, null=True)),
                ('password', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'dor_stu_account',
                'managed': True,
            },
        ),
        migrations.AlterModelOptions(
            name='activity',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='activity_applyment',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='adminstrator',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='bill',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='book_applyment',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='device',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='device_applyment',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='dor',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='dor_applyment',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='dor_cancel',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='dor_change',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='dormintory',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='live_on_vacation',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='meeting_room',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='meeting_room_applyment',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='meeting_room_time_quantunum',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='pay_bill',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='repair_device',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='routine_applyments',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='vacation_time_quantum',
            options={'managed': True},
        ),
        migrations.RemoveField(
            model_name='live_on_vacation',
            name='ad_no',
        ),
        migrations.RemoveField(
            model_name='live_on_vacation',
            name='is_apply_cancel',
        ),
        migrations.RemoveField(
            model_name='live_on_vacation',
            name='is_apply_success',
        ),
        migrations.AddField(
            model_name='live_on_vacation',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='activity_applyment',
            name='is_apply_cancel',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='activity_applyment',
            name='is_apply_success',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='book',
            name='is_borrowed',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='book_applyment',
            name='is_apply_cancel',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='book_applyment',
            name='is_apply_success',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='device_applyment',
            name='is_apply_cancel',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='device_applyment',
            name='is_apply_success',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='dor_cancel',
            name='phone',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='dor_cancel',
            name='reason',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='dor_change',
            name='phone',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='dor_change',
            name='reason',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='live_on_vacation',
            name='dor_no',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='live_on_vacation',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='live_on_vacation',
            name='from_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='live_on_vacation',
            name='reason',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='live_on_vacation',
            name='sname',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='meeting_room',
            name='is_occupied',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='meeting_room',
            name='medium',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='meeting_room_applyment',
            name='is_apply_cancel',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='meeting_room_applyment',
            name='is_apply_success',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='pay_bill',
            name='is_paied',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterModelTable(
            name='activity',
            table='dor_activity',
        ),
        migrations.AlterModelTable(
            name='activity_applyment',
            table='dor_activity_applyment',
        ),
        migrations.AlterModelTable(
            name='adminstrator',
            table='dor_adminstrator',
        ),
        migrations.AlterModelTable(
            name='bill',
            table='dor_bill',
        ),
        migrations.AlterModelTable(
            name='book',
            table='dor_book',
        ),
        migrations.AlterModelTable(
            name='book_applyment',
            table='dor_book_applyment',
        ),
        migrations.AlterModelTable(
            name='device',
            table='dor_device',
        ),
        migrations.AlterModelTable(
            name='device_applyment',
            table='dor_device_applyment',
        ),
        migrations.AlterModelTable(
            name='dor',
            table='dor_dor',
        ),
        migrations.AlterModelTable(
            name='dor_applyment',
            table='dor_dor_applyment',
        ),
        migrations.AlterModelTable(
            name='dor_cancel',
            table='dor_dor_cancel',
        ),
        migrations.AlterModelTable(
            name='dor_change',
            table='dor_dor_change',
        ),
        migrations.AlterModelTable(
            name='dormintory',
            table='dor_dormintory',
        ),
        migrations.AlterModelTable(
            name='live_on_vacation',
            table='dor_live_on_vacation',
        ),
        migrations.AlterModelTable(
            name='meeting_room',
            table='dor_meeting_room',
        ),
        migrations.AlterModelTable(
            name='meeting_room_applyment',
            table='dor_meeting_room_applyment',
        ),
        migrations.AlterModelTable(
            name='meeting_room_time_quantunum',
            table='dor_meeting_room_time_quantunum',
        ),
        migrations.AlterModelTable(
            name='organization',
            table='dor_organization',
        ),
        migrations.AlterModelTable(
            name='pay_bill',
            table='dor_pay_bill',
        ),
        migrations.AlterModelTable(
            name='repair_device',
            table='dor_repair_device',
        ),
        migrations.AlterModelTable(
            name='room',
            table='dor_room',
        ),
        migrations.AlterModelTable(
            name='routine_applyments',
            table='dor_routine_applyments',
        ),
        migrations.AlterModelTable(
            name='student',
            table='dor_student',
        ),
        migrations.AlterModelTable(
            name='vacation_time_quantum',
            table='dor_vacation_time_quantum',
        ),
        migrations.AlterUniqueTogether(
            name='admin_show_change_dor_log',
            unique_together=set([('sno', 'apply_time')]),
        ),
    ]
